SET PATH=C:\DevTools\Keil_v5\ARM\ARMCLANG\Bin;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Bandizip\;C:\Program Files\dotnet\;C:\DevTools\Git\cmd;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Incredibuild;C:\Users\liuyu\.cargo\bin;C:\Users\liuyu\scoop\shims;C:\Users\liuyu\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\liuyu\AppData\Local\Programs\Python\Python311\;C:\Users\liuyu\AppData\Local\Microsoft\WindowsApps;C:\Users\liuyu\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\liuyu\AppData\Local\Programs\oh-my-posh\bin;C:\DevTools\msys64\ucrt64\bin;C:\DevTools\msys64\mingw64\bin;;C:\Program Files\JetBrains\PyCharm 2022.1.3\bin;;C:\Users\liuyu\.dotnet\tools
SET CPU_TYPE=CS32F103C8
SET CPU_VENDOR=AutoChips
SET UV2_TARGET=STM32F103C8T6
SET CPU_CLOCK=0x00B71B00
"C:\DevTools\Keil_v5\ARM\ARMCLANG\Bin\ArmClang.exe" @"stm32f103c8t6\main.__i"
"C:\DevTools\Keil_v5\ARM\ARMCLANG\Bin\ArmClang.exe" @"stm32f103c8t6\gpio.__i"
"C:\DevTools\Keil_v5\ARM\ARMCLANG\Bin\ArmClang.exe" @"stm32f103c8t6\crc.__i"
"C:\DevTools\Keil_v5\ARM\ARMCLANG\Bin\ArmClang.exe" @"stm32f103c8t6\iwdg.__i"
"C:\DevTools\Keil_v5\ARM\ARMCLANG\Bin\ArmClang.exe" @"stm32f103c8t6\tim.__i"
"C:\DevTools\Keil_v5\ARM\ARMCLANG\Bin\ArmClang.exe" @"stm32f103c8t6\usart.__i"
"C:\DevTools\Keil_v5\ARM\ARMCLANG\Bin\ArmClang.exe" @"stm32f103c8t6\stm32f1xx_it.__i"
"C:\DevTools\Keil_v5\ARM\ARMCLANG\Bin\ArmClang.exe" @"stm32f103c8t6\stm32f1xx_hal_msp.__i"
"C:\DevTools\Keil_v5\ARM\ARMCLANG\Bin\ArmClang.exe" @"stm32f103c8t6\dma.__i"
"C:\DevTools\Keil_v5\ARM\ARMCLANG\Bin\ArmLink" --Via "STM32F103C8T6\STM32F103C8T6.lnp"
